name: Merge Action
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.4
      - run: bun install -y
      - name: Install Vercel CLI
        run: bun add --global vercel@latest
      - name: Get NX BASE and NX HEAD
        uses: nrwl/nx-set-shas@v4
      - name: Check PR is merged to main
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_MERGER="${{ github.event.pull_request.merged_by.login }}"
          PR_REVIEWER="${{ github.event.pull_request.requested_reviewers[0].login }}"
          echo "PR Author: $PR_AUTHOR"
          echo "PR Merger: $PR_MERGER"
          echo "PR Reviewer: $PR_REVIEWER"
           
          if [ "$PR_MERGER" == "amar9elbeg" ]; then
            echo "Merge stopped: PR Merger is not allowed to merge."
            exit 1  
          fi
      - name: Generating Preview
        id: preview-deployment
        run: |
          export NX_BASE=${{ env.NX_BASE }}
          export NX_HEAD=${{ env.NX_HEAD }}
          export VERCEL_TOKEN=${{ env.VERCEL_TOKEN }}
          bash ./tools/scripts/merge.sh
