name: Merge Action
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      MONGOL_API_WEB_PRO_ID: ${{ secrets.MONGOL_API_WEB_PRO_ID }}
      MONGOL_API_IMAGES_SERVICE_PRO_ID: ${{ secrets.MONGOL_API_IMAGES_SERVICE_PRO_ID }}
      MONGOL_API_REST_PRO_ID: ${{ secrets.MONGOL_API_REST_PRO_ID }}
      MONGOL_API_GRAPHQL_PRO_ID: ${{ secrets.MONGOL_API_GRAPHQL_PRO_ID }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.4
      - run: bun install -y
      - name: Install Vercel CLI
        run: bun add --global vercel@latest
      - name: Get NX BASE and NX HEAD
        uses: nrwl/nx-set-shas@v4
      - name: Generating Preview
        id: preview-deployment
        run: |
          export NX_BASE=${{ env.NX_BASE }}
          export NX_HEAD=${{ env.NX_HEAD }}
          export VERCEL_TOKEN=${{ env.VERCEL_TOKEN }}
          bash ./tools/scripts/merge.sh
