name: Mongol Api Rest PR Action workflow
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'apps/mongol-api-rest/**'
      - '!libs/**'
      - '!shared/**'
jobs:
  Mongol-Api-Rest-Pull-Request-Action:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.4
      - run: bun install
      - name: Install Vercel CLI
        run: bun add --global vercel@latest
      - name: Run tests
        run: bunx nx test mongol-api-rest
      - name: Deploy to Vercel
        id: deployment
        run: |
          export VERCEL_TOKEN=${{ env.VERCEL_TOKEN }} 
          output_vercel=$(bunx nx preview mongol-api-rest)
          echo "Output of 'bunx nx preview': $output_vercel"  # Add this line
          preview_link=$(echo "$output_vercel" | grep -Eo 'https://[^ >]+\.vercel\.app' | tail -1)
          echo "Preview Link: $preview_link"  # Add this line
          echo "ACTION_OUTPUT=${preview_link}" >> $GITHUB_ENV
      - name: Add the preview report to pull request
        uses: mshick/add-pr-comment@v2
        with:
          message: 'Preview link for Mongol-Api-Rest: ${{ env.ACTION_OUTPUT }}'
